version: "2.1"
services:
#  psql:
#    build: postgres
#    ports:
#      - "5432:5432"
#  mongodb:
#    image: mongo
#    ports:
#      - "27017:27017"
#  mongo-seed:
#    build: mongo-seed
#    links:
#      - mongodb
  elastic:
    image: elasticsearch
    ports:
      - "9200:9200"
  elastic-seed:
    build: elastic-seed
    links:
      - elastic
    depends-on:
      - elastic
#  kibana:
#    image: kibana
#    links:
#      - elastic
#    ports:
#      - "5601:5601"

